import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import '../../data/models/project_model.dart';
import '../../core/utils/calculations.dart';
import '../../core/theme/app_theme.dart';

class ReportScreen extends StatelessWidget {
  final ProjectModel project;

  const ReportScreen({super.key, required this.project});

  Future<void> _generateAndShare() async {
    final buffer = StringBuffer();
    buffer.writeln('═══════════════════════════════════════');
    buffer.writeln('           GEO MASTER REPORT');
    buffer.writeln('═══════════════════════════════════════');
    buffer.writeln('');
    buffer.writeln('Project: ${project.name}');
    buffer.writeln('Description: ${project.description}');
    buffer.writeln('Coordinate System: ${project.coordinateSystem}');
    buffer.writeln('Created: ${project.createdAt}');
    buffer.writeln('Updated: ${project.updatedAt}');
    buffer.writeln('');
    buffer.writeln('───────────────────────────────────────');
    buffer.writeln('SUMMARY');
    buffer.writeln('───────────────────────────────────────');
    buffer.writeln('Points:   ${project.points.length}');
    buffer.writeln('Lines:    ${project.lines.length}');
    buffer.writeln('Polygons: ${project.polygons.length}');
    buffer.writeln('');

    if (project.points.isNotEmpty) {
      buffer.writeln('───────────────────────────────────────');
      buffer.writeln('POINTS');
      buffer.writeln('───────────────────────────────────────');
      buffer.writeln('${'Name'.padRight(12)} ${'Latitude'.padRight(14)} ${'Longitude'.padRight(14)} ${'Alt'.padRight(8)} Acc');
      for (var p in project.points) {
        buffer.writeln('${p.name.padRight(12)} ${p.latitude.toStringAsFixed(8).padRight(14)} ${p.longitude.toStringAsFixed(8).padRight(14)} ${p.altitude.toStringAsFixed(2).padRight(8)} ±${p.accuracy.toStringAsFixed(1)}m');
      }
      buffer.writeln('');
    }

    if (project.lines.isNotEmpty) {
      buffer.writeln('───────────────────────────────────────');
      buffer.writeln('LINES');
      buffer.writeln('───────────────────────────────────────');
      for (var l in project.lines) {
        buffer.writeln('${l.name}: ${l.length.toStringAsFixed(2)} m  (${l.points.length} points)');
      }
      buffer.writeln('');
    }

    if (project.polygons.isNotEmpty) {
      buffer.writeln('───────────────────────────────────────');
      buffer.writeln('POLYGONS / AREAS');
      buffer.writeln('───────────────────────────────────────');
      for (var poly in project.polygons) {
        buffer.writeln('${poly.name}:');
        buffer.writeln('  Area:      ${poly.area.toStringAsFixed(2)} m²');
        buffer.writeln('  Perimeter: ${poly.perimeter.toStringAsFixed(2)} m');
        final vol = SurveyCalculations.volumeFromPolygon(poly);
        buffer.writeln('  Est.Volume (ref=0): ${vol.toStringAsFixed(2)} m³');
        buffer.writeln('');
      }
    }

    buffer.writeln('───────────────────────────────────────');
    buffer.writeln('Generated by Geo Master');
    buffer.writeln(DateTime.now().toString());
    buffer.writeln('═══════════════════════════════════════');

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${project.name}_report.txt');
    await file.writeAsString(buffer.toString());
    await Share.shareXFiles([XFile(file.path)], text: 'Geo Master Survey Report');
  }

  @override
  Widget build(BuildContext context) {
    final totalLength = project.lines.fold<double>(0, (s, l) => s + l.length);
    final totalArea = project.polygons.fold<double>(0, (s, p) => s + p.area);

    return Scaffold(
      appBar: AppBar(title: Text('report'.tr())),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(project.name, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                  if (project.description.isNotEmpty)
                    Text(project.description, style: TextStyle(color: Colors.grey.shade600)),
                  const SizedBox(height: 12),
                  _row('points'.tr(), '${project.points.length}'),
                  _row('lines'.tr(), '${project.lines.length}'),
                  _row('polygons'.tr(), '${project.polygons.length}'),
                  const Divider(),
                  _row('total_length'.tr(), '${totalLength.toStringAsFixed(2)} m'),
                  _row('total_area'.tr(), '${totalArea.toStringAsFixed(2)} m²'),
                ],
              ),
            ),
          ),
          const SizedBox(height: 16),
          if (project.polygons.isNotEmpty) ...[
            Text('volumes'.tr(), style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            const SizedBox(height: 8),
            ...project.polygons.map((poly) {
              final vol = SurveyCalculations.volumeFromPolygon(poly);
              return Card(
                child: ListTile(
                  title: Text(poly.name),
                  subtitle: Text('${'area'.tr()}: ${poly.area.toStringAsFixed(1)} m²'),
                  trailing: Text(
                    '${vol.toStringAsFixed(1)} m³',
                    style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.primaryColor),
                  ),
                ),
              );
            }),
            const SizedBox(height: 16),
          ],
          ElevatedButton.icon(
            onPressed: _generateAndShare,
            icon: const Icon(Icons.picture_as_pdf),
            label: Text('generate_report'.tr()),
            style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 14)),
          ),
        ],
      ),
    );
  }

  Widget _row(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: TextStyle(color: Colors.grey.shade600)),
          Text(value, style: const TextStyle(fontWeight: FontWeight.bold)),
        ],
      ),
    );
  }
}
